name: deploy-git
run-name: Deploy using Git
on: [push]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
      - uses: oleksiyrudenko/gha-git-credentials@v2.1.1
        with:
          global: true
          name: "Oleksiy Rudenko"
          email: "oleksiy.rudenko@domain.com"
          actor: "OleksiyRudenko"
          token: "${{ secrets.GL_PAT_WEB_CENTRAL }}"
      - name: switching from HTTPS to SSH
        run: git remote set-url origin ${{ secrets.ssh }} git@github.com:Pranshu1902/workflows.git
      - name: check for changes
        run: git status
      - name: stage changed files
        run: git add .
      - name: commit changed files
        run: git commit -m "Auto updating blog.json"
      - name: fetch from master
        run: git fetch origin master
      - name: push code to master
        run: git push origin HEAD:master
