name: medium-api
run-name: Pranshu's blog extraction
on: [push]
permissions:
  contents: write
jobs:
  conditional_job_check_files:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.filter.outputs.workflows }}
    steps:
      - uses: actions/checkout@v3
        with:
          repository: "Pranshu1902/workflows"
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            workflows:
              - '.github/workflows/**'
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      - name: install dependencies
        run: |
          python -m pip install 'requests'
          python -m pip install 'bs4'
      - name: execute py script # run the run.py to get the latest data
        run: |
          python ./.github/workflows/medium.py

      # - name: save to artifact
      #   run: |
      #     mkdir -p ./src/data.json
      #     echo ./src/data.json > ./src/blog.json

      # - uses: actions/upload-artifact@v2
      #   with:
      #     name: blogData
      #     path: ./src/blog.json

      # run only if 'workflows' files were changed
      # - name: workflow tests
      #   if: steps.filter.outputs.workflows == 'true'
      #   run: echo "Workflow file"

      # # run only if not 'workflows' files were changed
      # - name: not workflow tests
      #   if: steps.filter.outputs.workflows != 'true'
      #   run: echo "NOT workflow file"

      - shell: pwsh
        # Give an id to the step, so we can reference it later
        id: check_file_changed
        run: |
          $diff = git diff

          $SourceDiff = $diff | Where-Object { $_ -match '^docs/' -or $_ -match '.json$' }
          $HasDiff = $SourceDiff.Length -gt 0

          Write-Host "::set-output name=docs_changed::$HasDiff"

      # Run the step only with "docs_changed" equals "True"
      - shell: pwsh
        # steps.<step_id>.outputs.<output name>
        if: steps.check_file_changed.outputs.docs_changed == 'True'
        run: echo publish docs

  publish:
    runs-on: ubuntu-latest
    needs: [conditional_job_check_files]
    if: needs.conditional_job_check_files.outputs.docs_changed == 'True'
    steps:
      - uses: actions/checkout@v3
        with:
          repository: "Pranshu1902/workflows"
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      - name: install dependencies
        run: |
          python -m pip install 'requests'
          python -m pip install 'bs4'
      - name: execute py script # run the run.py to get the latest data
        run: |
          python ./.github/workflows/medium.py
      - name: switching from HTTPS to SSH
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      - name: check for changes
        run: git status
      - name: stage changed files
        run: git add .
      - name: commit changed files
        run: git commit -m "Auto updating blog.json"
      - name: fetch from master
        run: git fetch origin master
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
