name: medium-api
run-name: Pranshu's blog extraction
on: [push]
permissions:
  contents: write
jobs:
  publish:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.check_file_changed.outputs.workflows }}
    env:
      updated: 'False'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
          repository: "Pranshu1902/workflows"
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      - name: install dependencies
        run: |
          python -m pip install 'requests'
          python -m pip install 'bs4'
      - name: execute py script # run the run.py to get the latest data
        run: |
          python ./.github/workflows/medium.py

      - shell: pwsh
        # Give an id to the step, so we can reference it later
        id: check_file_changed
        run: |
          # Diff HEAD with the previous commit
          $diff = git diff --name-only HEAD^ HEAD

          # Check if a file under docs/ or with the .md extension has changed (added, modified, deleted)
          $SourceDiff = $diff | Where-Object { $_ -match '^docs/' -or $_ -match '.json$' }
          $HasDiff = $SourceDiff.Length -gt 0

          $updated = $HasDiff

      - name: check
        if: ${{ updated == 'True' }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git status
          git add .
          git commit -m "Auto updating blog.json"
          git fetch origin master

      - name: Push changes
        if: ${{ updated == 'True'}}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
